name: foodie
description: "Personal application - recipes of dishes and desserts"

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.3.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl: any
  cupertino_icons: ^1.0.6
  shared_preferences: ^2.2.3
  provider: ^6.1.2
  url_launcher: ^6.3.1
  font_awesome_flutter: ^10.8.0
  sqflite: ^2.3.3+1
  logger: ^2.6.0
  flutter_slidable: ^3.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0

flutter:
  generate: true
  uses-material-design: true
  fonts:
    - family: RobotoMono
      fonts:
        - asset: assets/RobotoMono-Light.ttf
          weight: 300
        - asset: assets/RobotoMono-Regular.ttf
          weight: 400
        - asset: assets/RobotoMono-Medium.ttf
          weight: 500
        - asset: assets/RobotoMono-Bold.ttf
          weight: 700
  assets:
    - assets/logo/foodie_logo.png
