name: widget_catalog
description: "Widgetbook for Foodie"
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter
  widgetbook: ^3.15.0
  widgetbook_annotation: ^3.6.0
  font_awesome_flutter: ^10.8.0
  foodie:
    path: ../

dev_dependencies:
  widgetbook_generator: ^3.14.0
  build_runner: ^2.4.9

flutter:
  uses-material-design: true
